name: mobile
description: "Projeto Flutter do EduMentor"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^8.0.2
  model_viewer_plus: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1" # ◄ Adicione esta linha

flutter:
  assets:
    - assets/images/arte.jpeg
    - assets/images/anatomia.jpeg
    - assets/images/fauna.jpeg
    - assets/images/astronomia.jpeg
    - assets/images/SplashScreen.png
    - assets/images/Logo.png



flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/iconeApp.png" # ◄ Caminho da sua imagem quadrada